spring.application.name=consumer
server.port=8092

# KAFKA
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=ong-empuje-comunitario
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.datasource.url=jdbc:mariadb://mariadb:3306/ong-empuje-comunitario
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Configuración de nuestra ONG
ong.id=1
ong.nombre=Empuje Comunitario