# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: donation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'donation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64onation.proto\x12\x08\x64onation\"\x07\n\x05\x45mpty\"b\n\x08\x44onation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tcategoria\x18\x02 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x04 \x01(\x05\x12\x10\n\x08username\x18\x05 \x01(\t\"4\n\x0c\x44onationList\x12$\n\x08\x64onation\x18\x01 \x03(\x0b\x32\x12.donation.Donation\",\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf9\x01\n\x0f\x44onationService\x12\x38\n\x0e\x43reateDonation\x12\x12.donation.Donation\x1a\x12.donation.Response\x12\x38\n\x0eUpdateDonation\x12\x12.donation.Donation\x1a\x12.donation.Response\x12\x38\n\x0e\x44\x65leteDonation\x12\x12.donation.Donation\x1a\x12.donation.Response\x12\x38\n\rListDonations\x12\x0f.donation.Empty\x1a\x16.donation.DonationListB\x17\n\x15\x63om.grpc.demo.serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'donation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.grpc.demo.service'
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_DONATION']._serialized_start=37
  _globals['_DONATION']._serialized_end=135
  _globals['_DONATIONLIST']._serialized_start=137
  _globals['_DONATIONLIST']._serialized_end=189
  _globals['_RESPONSE']._serialized_start=191
  _globals['_RESPONSE']._serialized_end=235
  _globals['_DONATIONSERVICE']._serialized_start=238
  _globals['_DONATIONSERVICE']._serialized_end=487
# @@protoc_insertion_point(module_scope)
