DROP TABLE IF EXISTS roles;

CREATE TABLE roles (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO roles (id, name) VALUES
(1, 'PRESIDENTE'),
(2, 'COORDINADOR'),
(3, 'VOLUNTARIO'),
(4, 'VOCAL');
