DROP TABLE IF EXISTS organizations;

CREATE TABLE organizations (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO organizations (id, name) VALUES
(1, 'ONG-EMPUJE-COMUNITARIO'),
(2, 'ONG-SOMOS-MAS'),
(3, 'ONG-CREANDO-LAZOS'),
(4, 'ONG-ABRIENDO-CAMINOS');
