spring.application.name=demo
server.port = 8081
grpc.client.user-service.address=static://localhost:50051
grpc.client.user-service.negotiation-type=plaintext
grpc.client.auth-service.address=static://localhost:50051
grpc.client.auth-service.negotiation-type=plaintext
grpc.client.donation-service.address=static://localhost:50051
grpc.client.donation-service.negotiation-type=plaintext
grpc.client.event-service.address=static://localhost:50051
grpc.client.event-service.negotiation-type=plaintext
logging.level.com.grpc.demo=DEBUG

# KAFKA
spring.kafka.bootstrap-servers=host.docker.internal:9092
spring.kafka.consumer.group-id=mi-grupo
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Configuración ONG
ong.id=1
ong.nombre=Empuje Comunitario